# Generated by Django 3.2.3 on 2022-05-04 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ตระกร้าสินค้า',
                'verbose_name_plural': 'ตระกร้าสินค้า',
                'db_table': 'cart',
                'ordering': ('date_added',),
            },
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'รายการสินค้าในตระกร้าสินค้า', 'verbose_name_plural': 'รายการสินค้าในตระกร้าสินค้า'},
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='cartItem',
        ),
        migrations.AddField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
    ]
